from __future__ import annotations

PHASE_PARSE = "parse"
PHASE_BATCH_INIT = "batch_init"
PHASE_BATCH_CLEANUP = "batch_cleanup"
PHASE_BATCH_CONTROL = "batch_control"
PHASE_BATCH_ENQUEUE = "batch_enqueue"
PHASE_MESSAGE_LOOP = "message_loop"
PHASE_MESSAGE_LOOP_STOP = "message_loop_stop"
PHASE_SUBSCRIPTION_ACK = "subscription_ack"
PHASE_TICKER_PROCESS = "ticker_process"
PHASE_TRADE_PROCESS = "trade_process"
PHASE_HEALTH_MONITOR_START = "health_monitor_start"
PHASE_HEALTH_MONITOR_STOP = "health_monitor_stop"
PHASE_HEARTBEAT_SEND = "heartbeat_send"
PHASE_HEARTBEAT_LOOP = "heartbeat_loop"
PHASE_WATCHDOG_IDLE = "watchdog_idle"
PHASE_WATCHDOG_LOOP = "watchdog_loop"
PHASE_CONNECTION_ERROR = "connection_error"
